language: r

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_packages:
  - covr

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libv8-dev
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -O3" >> ~/.R/Makevars

after_success:
  - Rscript -e 'library(covr); codecov()'