name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: [3.x]
    steps:
    - name: Generate coverage report
      run: |
        R CMD CHECK
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
